os:
  - linux
  - osx
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
sudo: false
compiler: clang
before_install:
  - npm install -g npm@3
  - npm install -g grunt-cli
install: npm install
before_script:
  - grunt test-examples
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/2f6f94ff359a6445b59d"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
env:
  - NO_SERIALPORT_INSTALL=1

after_success:
  - npm run test-cover && npm run coveralls
